server:
  port: 8092
spring:
  application:
    name: user-service-config
  profiles:
    active: local
user:
    application:
        schema: ibsmp
        server: s227va6
        digitalId: v*+)y7%k^^-ch-0d7mh@wjl!i6yby8=rl2jmxmq%ct-xwv7@ox
        pingKey: MTIyNDQ3Nzg4MTEyMjQ0Nzc4ODExMjI0
        seal: intersello36
        deskey: Gb9uMp4fwio=
        deskey2: 8LGKin+HiIk=
        mstkenc: S8W91ti2Y/4=
        mstkenc2: S8W91ti2Y/4=
        datasource:
            oracle:
                jndi-name: jdbc/AppDataSource
            sql:
                persona:
                    jndi-name: jdbc/InterbankDataSource
        config:
            path: file:///C:/Apps/UserService/config
        flags:
            extracash: false
            session: false
        sessionTimeout: 7200000
        sessionInactiveTimeout: 300000